In [1]:
import numpy as np
from numpy import load

data = load('surfex_x_and_u_07100101-17123123.npz') 

In [2]:
arr_0 = np.array(data['arr_0'])
arr_1 = np.array(data['arr_1'])

In [3]:
arr_0[1]

array([ 2.818000e+02,  8.192515e-03,  2.200000e+00,  1.800000e+02,
       -0.000000e+00,  0.000000e+00,  3.558000e+02,  1.001400e+05,
        0.000000e+00,  1.670000e-04,  6.200000e-04], dtype=float32)

In [4]:
np.shape(arr_0)

(89879, 11)

In [9]:
arr_0[0]

array([ 2.825000e+02,  7.755806e-03,  2.500000e+00,  1.800000e+02,
       -0.000000e+00,  0.000000e+00,  3.561000e+02,  1.001800e+05,
        0.000000e+00,  0.000000e+00,  6.200000e-04], dtype=float32)

In [5]:
np.shape(arr_1)

(89879, 2, 90)

In [10]:
arr_1[0] #on a des 10**20 donc on est sur de la neige, où en l'occurrence on n'a pas de neige mdr
#22 valeurs avant d'avoir des 10**20

array([[2.8322641e+02, 2.8524847e+02, 2.8748837e+02, 2.8797354e+02,
        2.8799969e+02, 2.8800000e+02, 2.8800092e+02, 2.8806512e+02,
        2.9197339e+02, 2.9199994e+02, 2.9200000e+02, 2.9200000e+02,
        2.9200000e+02, 2.9200000e+02, 1.7349450e-01, 2.0664148e-01,
        2.2331928e-01, 2.3470782e-01, 2.4406695e-01, 2.5009769e-01,
        2.5446537e-01, 2.5773627e-01, 1.0000000e+20, 1.0000000e+20,
        1.0000000e+20, 1.0000000e+20, 1.0000000e+20, 1.0000000e+20,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        1.0000000e+20, 1.0000000e+20, 1.0000000e+20, 1.0000000e+20,
        1.0000000e+20, 1.0000000e+20, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 1.0000000e+20, 1.0000000e+20,
        1.0000000e+20, 1.0000000e+20, 1.0000000e

In [11]:
arr_1[0][0] #on est au temps 0 et sur la particule 0? 

array([2.8322641e+02, 2.8524847e+02, 2.8748837e+02, 2.8797354e+02,
       2.8799969e+02, 2.8800000e+02, 2.8800092e+02, 2.8806512e+02,
       2.9197339e+02, 2.9199994e+02, 2.9200000e+02, 2.9200000e+02,
       2.9200000e+02, 2.9200000e+02, 1.7349450e-01, 2.0664148e-01,
       2.2331928e-01, 2.3470782e-01, 2.4406695e-01, 2.5009769e-01,
       2.5446537e-01, 2.5773627e-01, 1.0000000e+20, 1.0000000e+20,
       1.0000000e+20, 1.0000000e+20, 1.0000000e+20, 1.0000000e+20,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       1.0000000e+20, 1.0000000e+20, 1.0000000e+20, 1.0000000e+20,
       1.0000000e+20, 1.0000000e+20, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 1.0000000e+20, 1.0000000e+20,
       1.0000000e+20, 1.0000000e+20, 1.0000000e+20, 1.0000000e

In [12]:
arr_1[0][1]
#24 lignes avant d'avoir des 10**20

array([2.8579962e+02, 2.8671207e+02, 2.8773984e+02, 2.8798587e+02,
       2.8799985e+02, 2.8800000e+02, 2.8800000e+02, 2.8800000e+02,
       2.8800003e+02, 2.8801306e+02, 2.9199347e+02, 2.9200000e+02,
       2.9200000e+02, 2.9200000e+02, 1.7348097e-01, 2.0670266e-01,
       2.2336648e-01, 2.3473772e-01, 2.4408007e-01, 2.5010195e-01,
       2.5446692e-01, 2.5773734e-01, 2.5118843e-01, 2.5118855e-01,
       1.0000000e+20, 1.0000000e+20, 1.0000000e+20, 1.0000000e+20,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 1.0000000e+20, 1.0000000e+20,
       1.0000000e+20, 1.0000000e+20, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 1.0000000e+20, 1.0000000e+20,
       1.0000000e+20, 1.0000000e+20, 1.0000000e+20, 1.0000000e

ce que je ne comprends pas : si cela représentait les couches et leurs variables, on devrait avoir au moins 14x3 = 42 valeurs qui correspondent au sol et donc où l'on n'a pas de neige donc pourquoi autant de 10**20 ??? 